name: Documentation

on: [push]
permissions: 
  contents: write
jobs:
  build-and-deploy:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        run: |
            mkdir docs && \
            xcodebuild docbuild -scheme NavigationSplitTab \
              -destination 'platform=macOS,variant=Mac Catalyst' \
              OTHER_DOCC_FLAGS="--transform-for-static-hosting --hosting-base-path navigationsplittab" \
              DOCC_OUTPUT_DIR=./docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
