name: Documentation

on:
  push:
    branches:
      - main

permissions: 
  contents: write
jobs:
  build-and-deploy:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        run: |
            mkdir archive && \
            xcodebuild docbuild -scheme NavigationSplitTab \
              -destination 'platform=macOS,variant=Mac Catalyst' \
              OTHER_DOCC_FLAGS="--transform-for-static-hosting --hosting-base-path navigationsplittab" \
              DOCC_OUTPUT_DIR=./archive && \
              $(xcrun --find docc) process-archive \
              transform-for-static-hosting ./archive/NavigationSplitTab.doccarchive \
              --output-path docs \
              --hosting-base-path navigationsplittab
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
